name: Build

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

concurrency:
  # Cancel any workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: build-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        plat: [linux, android]
        os: ['20.04', '22.04']
        arch: [x86, x64] # arm64?
        tls: [openssl, openssl3]
        static: ['', '-Static']
        clang: ['', '-Clang']
        codecheck: ['', '-CodeCheck']
        exclude:
        - plat: android
          arch: x86       # Android doesn't support x86
        - plat: android
          clang: '-Clang' # Android doesn't use Clang
        - plat: android
          codecheck: '-CodeCheck' # Android doesn't use CodeCheck
    runs-on: ubuntu-${{ matrix.os }}
    name: Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Prepare Machine
      shell: pwsh
      run: scripts/prepare-machine.ps1 -ForBuild -Tls ${{ matrix.tls }}
    - name: Build Debug
      shell: pwsh
      run: scripts/build.ps1 -Config Debug -Platform ${{ matrix.plat }} -Arch ${{ matrix.arch }} -Tls ${{ matrix.tls }} ${{ matrix.static }} ${{ matrix.clang }} ${{ matrix.codecheck }}
    - name: Build Release
      if: ${{ matrix.codecheck }} != '-CodeCheck' # Release builds with CodeCheck fail - TODO: FIX
      shell: pwsh
      run: scripts/build.ps1 -Config Release -Platform ${{ matrix.plat }} -Arch ${{ matrix.arch }} -Tls ${{ matrix.tls }} ${{ matrix.static }} ${{ matrix.clang }} ${{ matrix.codecheck }}
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: ${{ matrix.plat }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.tls }}${{ matrix.static }}${{ matrix.clang }}${{ matrix.codecheck }}
        path: artifacts/bin

  build-macOS:
    needs: []
    strategy:
      fail-fast: false
      matrix:
        plat: [macos, ios]
        os: ['12']
        arch: [x86, x64, arm64]
        tls: [openssl, openssl3]
        static: ['', '-Static']
        exclude:
        - plat: ios
          arch: x86       # iOS doesn't support x86
    runs-on: macos-${{ matrix.os }}
    name: Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Prepare Machine
      shell: pwsh
      run: scripts/prepare-machine.ps1 -ForBuild -Tls ${{ matrix.tls }}
    - name: Build Debug
      shell: pwsh
      run: scripts/build.ps1 -Config Debug -Platform ${{ matrix.plat }} -Arch ${{ matrix.arch }} -Tls ${{ matrix.tls }} ${{ matrix.static }}
    - name: Build Release
      shell: pwsh
      run: scripts/build.ps1 -Config Release -Platform ${{ matrix.plat }} -Arch ${{ matrix.arch }} -Tls ${{ matrix.tls }} ${{ matrix.static }}
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: ${{ matrix.plat }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.tls }}${{ matrix.static }}
        path: artifacts/bin

  build-windows:
    needs: []
    strategy:
      fail-fast: false
      matrix:
        plat: [windows, uwp] # gamecore_console
        os: ['2019', '2022']
        arch: [x86, x64, arm64]
        tls: [schannel, openssl, openssl3]
        static: ['', '-Static']
        xdp: ['', '-UseXdp']
        exclude:
        - tls: openssl
          arch: arm64       # OpenSSL doesn't support arm64
        - tls: openssl3
          arch: arm64       # OpenSSL3 doesn't support arm64
        - plat: uwp
          tls: openssl3     # OpenSSL3 build fails with UWP
        - plat: uwp
          static: '-Static' # Static builds fail with UWP - TODO: FIX
        - plat: uwp
          xdp: '-UseXdp'    # XDP not supported in UWP
        - arch: x86
          xdp: '-UseXdp'    # XDP only supports x64 currently
        - arch: arm64
          xdp: '-UseXdp'    # XDP only supports x64 currently
    runs-on: windows-${{ matrix.os }}
    name: Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Install Perl
      uses: shogo82148/actions-setup-perl@e0737ade83f9863f9f5c00d8470b6d7bec207fee
      with:
        perl-version: '5.34'
    - name: Install NASM
      uses: ilammy/setup-nasm@321e6ed62a1fc77024a3bd853deb33645e8b22c4
    - name: Prepare Machine
      shell: pwsh
      run: scripts/prepare-machine.ps1 -ForBuild -Tls ${{ matrix.tls }}
    - name: Build Debug
      shell: pwsh
      run: scripts/build.ps1 -Config Debug -Platform ${{ matrix.plat }} -Arch ${{ matrix.arch }} -Tls ${{ matrix.tls }} ${{ matrix.static }} ${{ matrix.xdp }}
    - name: Build Release
      shell: pwsh
      run: scripts/build.ps1 -Config Release -Platform ${{ matrix.plat }} -Arch ${{ matrix.arch }} -Tls ${{ matrix.tls }} ${{ matrix.static }} ${{ matrix.xdp }}
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: ${{ matrix.plat }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.tls }}${{ matrix.static }}${{ matrix.xdp }}
        path: |
          artifacts/bin
          !artifacts/bin/xdp
          !artifacts/bin/**/*.ilk
          !artifacts/bin/**/*.cer
          !artifacts/bin/**/*.exp
          !artifacts/bin/**/*.lastcodeanalysissucceeded
          !artifacts/bin/**/*.pgd
          !artifacts/bin/**/*.lib

  build-windows-kernel:
    needs: []
    strategy:
      fail-fast: false
      matrix:
        plat: [winkernel]
        os: ['2019', '2022']
        arch: [x64, arm64]
        tls: [schannel]
    runs-on: windows-${{ matrix.os }}
    name: Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Prepare Machine
      shell: pwsh
      run: scripts/prepare-machine.ps1 -ForBuild -ForKernel
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@34cfbaee7f672c76950673338facd8a73f637506
    - name: Nuget Restore Debug
      shell: pwsh
      run: msbuild msquic.kernel.sln -t:restore /p:RestorePackagesConfig=true /p:Configuration=Debug /p:Platform=${{ matrix.arch }}
    - name: Build Debug
      shell: pwsh
      run: msbuild msquic.kernel.sln /p:Configuration=Debug /p:Platform=${{ matrix.arch }} /p:QUIC_VER_SUFFIX=-official
    - name: Nuget Restore Release
      shell: pwsh
      run: msbuild msquic.kernel.sln -t:restore /p:RestorePackagesConfig=true /p:Configuration=Release /p:Platform=${{ matrix.arch }}
    - name: Build Release
      shell: pwsh
      run: msbuild msquic.kernel.sln /p:Configuration=Release /p:Platform=${{ matrix.arch }} /p:QUIC_VER_SUFFIX=-official
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: ${{ matrix.plat }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.tls }}
        path: |
          artifacts/bin
          !artifacts/bin/xdp
          !artifacts/bin/**/*.ilk
          !artifacts/bin/**/*.cer
          !artifacts/bin/**/*.exp
          !artifacts/bin/**/*.lastcodeanalysissucceeded
          !artifacts/bin/**/*.pgd
          !artifacts/bin/**/*.lib
