name: Build

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

concurrency:
  # Cancel any workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: build-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        plat: [linux, android]
        arch: [x86, x64] # arm64?
        tls: [openssl, openssl3]
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Prepare Machine
      run: scripts/prepare-machine.ps1 -ForBuild -Tls ${{ matrix.tls }}
      shell: pwsh
    - name: Build Debug
      shell: pwsh
      run: scripts/build.ps1 -Config Debug -Platform ${{ matrix.plat }} -Arch ${{ matrix.arch }} -Tls ${{ matrix.tls }}
    - name: Build Release
      shell: pwsh
      run: scripts/build.ps1 -Config Release -Platform ${{ matrix.plat }} -Arch ${{ matrix.arch }} -Tls ${{ matrix.tls }}
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: bin-${{ matrix.os }}-${{ matrix.plat }}-${{ matrix.arch }}-${{ matrix.tls }}
        path: |
          artifacts/bin
          !artifacts/bin/**/*.ilk
          !artifacts/bin/**/*.cer
          !artifacts/bin/**/*.exp
          !artifacts/bin/**/*.lastcodeanalysissucceeded
          !artifacts/bin/**/*.pgd
          !artifacts/bin/**/*.lib
  build-macOS:
    needs: []
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        plat: [macos, iso]
        arch: [x86, x64, arm64]
        tls: [openssl, openssl3]
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Prepare Machine
      run: scripts/prepare-machine.ps1 -ForBuild -Tls ${{ matrix.tls }}
      shell: pwsh
    - name: Build Debug
      shell: pwsh
      run: scripts/build.ps1 -Config Debug -Platform ${{ matrix.plat }} -Arch ${{ matrix.arch }} -Tls ${{ matrix.tls }}
    - name: Build Release
      shell: pwsh
      run: scripts/build.ps1 -Config Release -Platform ${{ matrix.plat }} -Arch ${{ matrix.arch }} -Tls ${{ matrix.tls }}
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: bin-${{ matrix.os }}-${{ matrix.plat }}-${{ matrix.arch }}-${{ matrix.tls }}
        path: |
          artifacts/bin
          !artifacts/bin/**/*.ilk
          !artifacts/bin/**/*.cer
          !artifacts/bin/**/*.exp
          !artifacts/bin/**/*.lastcodeanalysissucceeded
          !artifacts/bin/**/*.pgd
          !artifacts/bin/**/*.lib
  build-windows:
    needs: []
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
        plat: [gamecore_console, uwp, windows]
        arch: [x86, x64, arm64]
        tls: [schannel, openssl, openssl3]
        exclude:
        - tls: openssl
          arch: arm64       # OpenSSL doesn't support arm64
        - tls: openssl3
          arch: arm64       # OpenSSL3 doesn't support arm64
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Install Perl
      uses: shogo82148/actions-setup-perl@e0737ade83f9863f9f5c00d8470b6d7bec207fee
      with:
        perl-version: '5.34'
    - name: Install NASM
      uses: ilammy/setup-nasm@321e6ed62a1fc77024a3bd853deb33645e8b22c4
    - name: Prepare Machine
      run: scripts/prepare-machine.ps1 -ForBuild -Tls ${{ matrix.tls }}
      shell: pwsh
    - name: Build Debug
      shell: pwsh
      run: scripts/build.ps1 -Config Debug -Platform ${{ matrix.plat }} -Arch ${{ matrix.arch }} -Tls ${{ matrix.tls }}
    - name: Build Release
      shell: pwsh
      run: scripts/build.ps1 -Config Release -Platform ${{ matrix.plat }} -Arch ${{ matrix.arch }} -Tls ${{ matrix.tls }}
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: bin-${{ matrix.os }}-${{ matrix.plat }}-${{ matrix.arch }}-${{ matrix.tls }}
        path: |
          artifacts/bin
          !artifacts/bin/**/*.ilk
          !artifacts/bin/**/*.cer
          !artifacts/bin/**/*.exp
          !artifacts/bin/**/*.lastcodeanalysissucceeded
          !artifacts/bin/**/*.pgd
          !artifacts/bin/**/*.lib
